### ISSUE TITLE
Botu更新无法下载

### ISSUE THREAD

**Issue by blownscarerow** [qinlili23333/BotuDecrypt#1]
大佬能再更新一下版本吗

**Comment by qinlili23333** [comment]
等博图寒假解锁全部ip访问（以前都会解锁）之后我准备重写这个项目了，我现在手头没有可以访问的网络条件

**Comment by qinlili23333** [comment]
搓了个新脚本应对博图更新
https://greasyfork.org/zh-CN/scripts/439049-botu-predator
用这个脚本截获PDF再本地搭建服务器
先这么用着，等我重写

**Comment by qinlili23333** [comment]
2.0.0以支持本地解密，请自行编译
